![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [3]:
import numpy as np

## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [27]:

my_array = np.arange(10) #crear arrays con un generador
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [28]:
my_array1= np.full((3,3), True)
print(my_array1)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Ejercicio 4
Extrae todos los impares de `my_array`

In [29]:
mask = (my_array%2 != 0)
print(mask)

print(my_array[mask])
#las mascaras de numpy son los bucles for de python


[False  True False  True False  True False  True False  True]
[1 3 5 7 9]


## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [83]:
#?
nuevo_array= my_array[my_array % 2 != 0] = -1
print(nuevo_array) 

-1


## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [85]:
 #?
nuevo_array2 = np.where(my_array %2 != 0, -1, my_array)
print(nuevo_array2)


[]


## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [35]:
array2 = my_array.reshape((2,5)) #dos dimensiones de 5 nums cada uno
print(array2)


[[0 1 2 3 4]
 [5 6 7 8 9]]


## Ejercicio 8
Concatena los siguientes arrays verticamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [89]:
#?
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

print(a,b)

np.concatenate([a,b], axis = 0)

[[0 1 2 3 4]
 [5 6 7 8 9]] [[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [90]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(a,b)

np.concatenate([a,b], axis = 1)


[[0 1 2 3 4]
 [5 6 7 8 9]] [[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa el método `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [91]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a, b)

array([2, 4])

## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [38]:
np.concatenate??

Call signature:  np.concatenate(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function concatenate>
Docstring:      
concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")

Join a sequence of arrays along an existing axis.

Parameters
----------
a1, a2, ... : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined.  If axis is None,
    arrays are flattened before use.  Default is 0.
out : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what concatenate would have returned if no
    out argument were specified.
dtype : str or dtype
    If provided, the destination array will have this dtype. Cannot be
    provided together with `out`.

    .. versionadded:: 1.20.0

casting : {'no', 'equiv', 'safe', 

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento del array
3. Accede al último elemento del array
4. Imprime por pantalla los numeros del 1 al 7

In [45]:
array3 = my_array*10
print(array3)
print(array3[0])
print(array3[-1])
print(array3[1:8])


[ 0 10 20 30 40 50 60 70 80 90]
0
90
[10 20 30 40 50 60 70]


## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [49]:
my_matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(my_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [52]:
secuencia = np.arange(1,50,3)
print(secuencia)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

In [56]:
secuencia = np.arange(4,1,-0.25)
print(secuencia)

[4.   3.75 3.5  3.25 3.   2.75 2.5  2.25 2.   1.75 1.5  1.25]


## Ejercicio 16
Lee la imagen "numpy.png"

![imagen](./img/numpy.png)

In [74]:
import matplotlib.pyplot as plt

imagen = plt.imread("./img/numpy.png")
imagen.shape

(306, 765, 4)

## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

In [62]:
array= np.full((4,1), 0)
print(array)

array_mod = array.reshape((2,2))
print(array_mod)


[[0]
 [0]
 [0]
 [0]]
[[0 0]
 [0 0]]


## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [65]:
shape = (4, 5, 3)

secuencia = np.random.randint(5, 20, size=(shape))
print(secuencia)

[[[15  6  5]
  [ 7  6 13]
  [14 15 14]
  [13  7 17]
  [16 16 13]]

 [[16 11 18]
  [10 16  5]
  [17 11 16]
  [14  8  6]
  [10 12 12]]

 [[14 17 12]
  [16 16  9]
  [ 5 11  6]
  [ 6  9 19]
  [ 5  9 18]]

 [[13  7  9]
  [ 9  5 14]
  [13 10 19]
  [ 8 19  6]
  [12 16 15]]]


## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [68]:
matriz = np.full((10,1), False)
print(matriz)

reshape = matriz.reshape((2,5))
print(reshape)

[[False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]]
[[False False False False False]
 [False False False False False]]


## Ejercicio 20
Dado el siguiente array

```Python
x =np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuántos elementos tiene cada dimensión?

In [69]:
x =np.random.randint(10, 20, size = (5,2,6))
print(x)

#5 matrices, 2 filas, 6 columnas con numeros aleatorios del 10 al 20

[[[17 17 12 13 17 10]
  [16 11 18 12 14 11]]

 [[19 12 18 11 10 10]
  [14 13 17 12 19 19]]

 [[19 14 10 14 11 12]
  [17 11 15 16 14 10]]

 [[15 11 12 15 11 18]
  [13 17 15 10 11 11]]

 [[18 19 12 16 11 16]
  [18 12 13 15 16 14]]]
