![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [1]:
import numpy as np

In [11]:

my_array = np.arange(10)
print(my_array)
print(my_array[9:0:-2])

[0 1 2 3 4 5 6 7 8 9]
[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [15]:
print(my_array[8:6:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [22]:
print(my_array[2::-1]) 

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [136]:
shape = (4, 5) 
secuencia = np.random.randint(1, 20, size=(shape)) 
print(secuencia)

print(secuencia[::-1,::-1])

[[18  6  7 13 15]
 [14 18  2  6 15]
 [ 7 17  3 17  6]
 [ 8  4 10  4 18]]
[[18  4 10  4  8]
 [ 6 17  3 17  7]
 [15  6  2 18 14]
 [15 13  7  6 18]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [30]:
print(secuencia)
# array = secuencia.reshape((2,-1))

array = secuencia[:2, :2]

print(array)

[[13  9  9 15  4]
 [19  3  5  7  3]
 [15 17  7 16 15]
 [16  4 15 12  5]]
[[13  9]
 [19  3]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [32]:
print(secuencia)
# array = secuencia.reshape((2,-1))

array = secuencia[:3, :3]
print(array)


[[13  9  9 15  4]
 [19  3  5  7  3]
 [15 17  7 16 15]
 [16  4 15 12  5]]
[[13  9  9]
 [19  3  5]
 [15 17  7]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [34]:
print(secuencia)
# array = secuencia.reshape((2,-1))

array = secuencia[:3, :5]
print(array)

[[13  9  9 15  4]
 [19  3  5  7  3]
 [15 17  7 16 15]
 [16  4 15 12  5]]
[[13  9  9 15  4]
 [19  3  5  7  3]
 [15 17  7 16 15]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [43]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

mask = (x== "Loro")
print(x[mask])


['Loro' 'Loro']


In [45]:
# print(x[-2]+' '+x[0])
x = np.where(x == "Loro", "Loro", "")
print(x)

['Loro' '' '' 'Loro' '']


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [135]:

secuencia = np.arange(20)

array = secuencia.reshape((5,2,2))
print(array)


[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]


## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [137]:
secuencia5 = secuencia.reshape((4, 5))
print(secuencia5)

[[18  6  7 13 15]
 [14 18  2  6 15]
 [ 7 17  3 17  6]
 [ 8  4 10  4 18]]


## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [95]:
array = np.zeros((3,3))
print(array)

array[1][0] = 1
print(array)

#cuanto ocupa en memoria:
print(array.nbytes)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 0. 0.]]
72


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [78]:
vector = np.arange(10,49)
print(vector)
invertido = vector[::-1]
print(invertido)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [90]:
vector = np.array([1,2,0,0,4,0])

x = np.array(vector)
y = np.nonzero(x)
print(y)


(array([0, 1, 4], dtype=int64),)


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [138]:
shape = (10,10)
matriz = np.random.randint(0,20, size = shape)
print(matriz.min())
print(matriz.max())

0
19


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [96]:
vector = np.arange(30)
print(vector.mean())

14.5


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [102]:
array = np.ones((8,8))
print(array)
array[1:-1,1:-1] = 0
array

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [126]:
matriz = np.zeros ((8,8))
matriz [1::2,0::2] = 1
matriz [::2, 1::2] = 1
matriz

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [124]:
np.tile(matriz,1)

array([[ 9.79687982,  0.79687982, 13.79687982, 16.79687982,  2.79687982],
       [12.79687982,  1.79687982, 11.79687982, 16.79687982, -0.20312018],
       [ 0.79687982, 16.79687982, 10.79687982,  3.79687982, 11.79687982],
       [ 4.79687982, 11.79687982,  9.79687982, 15.79687982,  9.79687982],
       [10.79687982, 15.79687982, 11.79687982, 14.79687982,  6.79687982]])

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [121]:
shape = (5,5)
matriz = np.random.randint(1, 20, size=(shape)) 
print(matriz)

matriz = matriz[:] - np.mean(matriz) / np.std(matriz)
matriz


[[12  3 16 19  5]
 [15  4 14 19  2]
 [ 3 19 13  6 14]
 [ 7 14 12 18 12]
 [13 18 14 17  9]]


array([[ 9.79687982,  0.79687982, 13.79687982, 16.79687982,  2.79687982],
       [12.79687982,  1.79687982, 11.79687982, 16.79687982, -0.20312018],
       [ 0.79687982, 16.79687982, 10.79687982,  3.79687982, 11.79687982],
       [ 4.79687982, 11.79687982,  9.79687982, 15.79687982,  9.79687982],
       [10.79687982, 15.79687982, 11.79687982, 14.79687982,  6.79687982]])

## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [133]:
secuencia = np.arange(10)
print(secuencia)

array = np.where((secuencia >= 3) & (secuencia <= 8), -1, secuencia)
print(array)
array = np.where((secuencia >= 3) & (secuencia <= 8), ' ', secuencia)
print(array)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2 -1 -1 -1 -1 -1 -1  9]
['0' '1' '2' ' ' ' ' ' ' ' ' ' ' ' ' '9']


## Ejercicio 21
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.